environment:
  matrix:
    - PYTHON: "C:\\Python27"
    # - PYTHON: "C:\\Python34" (disabled, fails)
    # - PYTHON: "C:\\Python36" (disabled, fails)

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest -m \"not slow\"" 

after_test:
  - "%PYTHON%\\python.exe setup.py sdist"

artifacts:
  - path: dist\*

#on_success:
#  noop - distribution is handled by Travis CI